language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
 - windows

jobs:
  allow_failures:
   - rust: nightly
   - os: windows
  fast_finish: true

before_script:
 - rustup component add rustfmt
 - rustup component add clippy

script:
 - rustfmt --check src/lib.rs
 - cargo clippy
 - cargo test
 - if [ "$RUST_BUILD" == "cargo" ]; then cargo doc --test; fi
