[package]
name = "rustact"
version = "0.1.0"
authors = ["not_a_seagull <notaseagull048@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[lib]
crate-type = ["cdylib", "rlib"]
proc_macro = true

[dependencies]
thiserror = "1.0.9"
